In [93]:
import numpy as np
import pandas as pd

In [94]:
date = pd.read_csv('date.csv')

In [95]:
date.head()

   ID        Date
0   1  2026-01-01
1   2  2026-01-02
2   3  2026-01-03
3   4  2026-01-04
4   5  2026-01-05

In [96]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      100 non-null    int64
 1   Date    100 non-null    object
dtypes: int64(1), object(1)
memory usage: 1.7+ KB

# Converting data type of data column

In [97]:
date['Date'] = pd.to_datetime(date['Date'])

In [98]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      100 non-null    int64
 1   Date    100 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(1)
memory usage: 1.7 KB

# Creating seprate column for Year Month And Date

In [99]:
date['Year']=date['Date'].dt.year
date['Month']=date['Date'].dt.month
date['Day']=date['Date'].dt.day

In [100]:
date

     ID       Date  Year  Month  Day
0     1 2026-01-01  2026      1    1
1     2 2026-01-02  2026      1    2
2     3 2026-01-03  2026      1    3
3     4 2026-01-04  2026      1    4
4     5 2026-01-05  2026      1    5
..  ...        ...   ...    ...  ...
95   96 2026-04-06  2026      4    6
96   97 2026-04-07  2026      4    7
97   98 2026-04-08  2026      4    8
98   99 2026-04-09  2026      4    9
99  100 2026-04-10  2026      4   10

[100 rows x 5 columns]

# Cretaing seprate column for month and day name

In [101]:
date['Month_Name'] = date['Date'].dt.month_name()
date['Day_Name'] = date['Date'].dt.day_name()

In [102]:
date

     ID       Date  Year  Month  Day Month_Name   Day_Name
0     1 2026-01-01  2026      1    1    January   Thursday
1     2 2026-01-02  2026      1    2    January     Friday
2     3 2026-01-03  2026      1    3    January   Saturday
3     4 2026-01-04  2026      1    4    January     Sunday
4     5 2026-01-05  2026      1    5    January     Monday
..  ...        ...   ...    ...  ...        ...        ...
95   96 2026-04-06  2026      4    6      April     Monday
96   97 2026-04-07  2026      4    7      April    Tuesday
97   98 2026-04-08  2026      4    8      April  Wednesday
98   99 2026-04-09  2026      4    9      April   Thursday
99  100 2026-04-10  2026      4   10      April     Friday

[100 rows x 7 columns]

# Day of week and is weekend columns

In [103]:
date['DOW'] = date['Date'].dt.dayofweek

In [104]:
date['Is_Weekend'] = np.where(date['Day_Name'].isin(['Saturday','Sunday']),1,9)

In [105]:
date

     ID       Date  Year  Month  Day Month_Name   Day_Name  DOW  Is_Weekend
0     1 2026-01-01  2026      1    1    January   Thursday    3           9
1     2 2026-01-02  2026      1    2    January     Friday    4           9
2     3 2026-01-03  2026      1    3    January   Saturday    5           1
3     4 2026-01-04  2026      1    4    January     Sunday    6           1
4     5 2026-01-05  2026      1    5    January     Monday    0           9
..  ...        ...   ...    ...  ...        ...        ...  ...         ...
95   96 2026-04-06  2026      4    6      April     Monday    0           9
96   97 2026-04-07  2026      4    7      April    Tuesday    1           9
97   98 2026-04-08  2026      4    8      April  Wednesday    2           9
98   99 2026-04-09  2026      4    9      April   Thursday    3           9
99  100 2026-04-10  2026      4   10      April     Friday    4           9

[100 rows x 9 columns]

# week column in context of year and qurater of year

In [106]:
date['Week_of_year'] = date['Date'].dt.isocalendar().week

In [109]:
date['Quarter_OF_Day'] = date['Date'].dt.quarter

In [111]:
date

,ID,Date,Year,Month,Day,Month_Name,Day_Name,DOW,Is_Weekend,Week_of_year,Quarter_OF_Day
0,1,2026-01-01,2026,1,1,January,Thursday,3,9,1,1
1,2,2026-01-02,2026,1,2,January,Friday,4,9,1,1
2,3,2026-01-03,2026,1,3,January,Saturday,5,1,1,1
3,4,2026-01-04,2026,1,4,January,Sunday,6,1,1,1
4,5,2026-01-05,2026,1,5,January,Monday,0,9,2,1
...,...,...,...,...,...,...,...,...,...,...,...
95,96,2026-04-06,2026,4,6,April,Monday,0,9,15,2
96,97,2026-04-07,2026,4,7,April,Tuesday,1,9,15,2
97,98,2026-04-08,2026,4,8,April,Wednesday,2,9,15,2
98,99,2026-04-09,2026,4,9,April,Thursday,3,9,15,2
99,100,2026-04-10,2026,4,10,April,Friday,4,9,15,2

# datetime module for calculations

In [119]:
import datetime
today = datetime.datetime.today()
print(today)

2026-06-30 21:29:47.252489

In [121]:
date['Time_Since_Day']=today - date['Date']

In [122]:
date

,ID,Date,Year,Month,Day,Month_Name,Day_Name,DOW,Is_Weekend,Week_of_year,Quarter_OF_Day,Time_Since_Day
0,1,2026-01-01,2026,1,1,January,Thursday,3,9,1,1,180 days 21:29:47.252489
1,2,2026-01-02,2026,1,2,January,Friday,4,9,1,1,179 days 21:29:47.252489
2,3,2026-01-03,2026,1,3,January,Saturday,5,1,1,1,178 days 21:29:47.252489
3,4,2026-01-04,2026,1,4,January,Sunday,6,1,1,1,177 days 21:29:47.252489
4,5,2026-01-05,2026,1,5,January,Monday,0,9,2,1,176 days 21:29:47.252489
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,2026-04-06,2026,4,6,April,Monday,0,9,15,2,85 days 21:29:47.252489
96,97,2026-04-07,2026,4,7,April,Tuesday,1,9,15,2,84 days 21:29:47.252489
97,98,2026-04-08,2026,4,8,April,Wednesday,2,9,15,2,83 days 21:29:47.252489
98,99,2026-04-09,2026,4,9,April,Thursday,3,9,15,2,82 days 21:29:47.252489
99,100,2026-04-10,2026,4,10,April,Friday,4,9,15,2,81 days 21:29:47.252489

In [126]:
(today - date['Date']).dt.days

0     180
1     179
2     178
3     177
4     176
     ...
95     85
96     84
97     83
98     82
99     81
Name: Date, Length: 100, dtype: int64

In [131]:
# Months passed

np.round((today - date['Date']) / np.timedelta64(1, 'D') / 30.44, 0)

0     6.0
1     6.0
2     6.0
3     6.0
4     6.0
     ...
95    3.0
96    3.0
97    3.0
98    3.0
99    3.0
Name: Date, Length: 100, dtype: float64

# Time handling

In [132]:
time = pd.read_csv('time.csv')

In [133]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        100 non-null    int64
 1   DateTime  100 non-null    object
dtypes: int64(1), object(1)
memory usage: 1.7+ KB

In [137]:
time['DateTime'] = pd.to_datetime(time['DateTime'])

In [138]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        100 non-null    int64
 1   DateTime  100 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(1)
memory usage: 1.7 KB

In [139]:
time

     ID            DateTime
0     1 2026-01-01 08:00:00
1     2 2026-01-01 11:00:00
2     3 2026-01-01 14:00:00
3     4 2026-01-01 17:00:00
4     5 2026-01-01 20:00:00
..  ...                 ...
95   96 2026-01-13 05:00:00
96   97 2026-01-13 08:00:00
97   98 2026-01-13 11:00:00
98   99 2026-01-13 14:00:00
99  100 2026-01-13 17:00:00

[100 rows x 2 columns]

In [143]:
time['Hour'] = time['DateTime'].dt.hour
time['Miniute']=time['DateTime'].dt.minute
time['Seconds']=time['DateTime'].dt.second

In [144]:
time

     ID            DateTime  Hour  Miniute  Seconds
0     1 2026-01-01 08:00:00     8        0        0
1     2 2026-01-01 11:00:00    11        0        0
2     3 2026-01-01 14:00:00    14        0        0
3     4 2026-01-01 17:00:00    17        0        0
4     5 2026-01-01 20:00:00    20        0        0
..  ...                 ...   ...      ...      ...
95   96 2026-01-13 05:00:00     5        0        0
96   97 2026-01-13 08:00:00     8        0        0
97   98 2026-01-13 11:00:00    11        0        0
98   99 2026-01-13 14:00:00    14        0        0
99  100 2026-01-13 17:00:00    17        0        0

[100 rows x 5 columns]

# Extracting time part from date and time

In [145]:
time['Time_Field'] = time['DateTime'].dt.time

In [146]:
time

     ID            DateTime  Hour  Miniute  Seconds Time_Field
0     1 2026-01-01 08:00:00     8        0        0   08:00:00
1     2 2026-01-01 11:00:00    11        0        0   11:00:00
2     3 2026-01-01 14:00:00    14        0        0   14:00:00
3     4 2026-01-01 17:00:00    17        0        0   17:00:00
4     5 2026-01-01 20:00:00    20        0        0   20:00:00
..  ...                 ...   ...      ...      ...        ...
95   96 2026-01-13 05:00:00     5        0        0   05:00:00
96   97 2026-01-13 08:00:00     8        0        0   08:00:00
97   98 2026-01-13 11:00:00    11        0        0   11:00:00
98   99 2026-01-13 14:00:00    14        0        0   14:00:00
99  100 2026-01-13 17:00:00    17        0        0   17:00:00

[100 rows x 6 columns]